DH3 Hide Sidebar
NYCPlanning/labs-zola pull request #1186
Opened 2024-03-28 15:04 UTC by dhochbaum-dcp

This PR {summarize the PR}

Changes Proposed:
- New Feature
- API change
- New Domain-specific language
- Refactor of existing code

Closes #{issue number(s)}

2024-05-01 18:55 UTC, bmarchena commented on app/controllers/application.js
> +
@dhochbaum-dcp I tried changing the class of the map container whenever the toggle is clicked here, but if you close the About section before toggling the sidebar the whitespace persists.

2024-05-08 17:03 UTC, TylerMatteo requested changes

2024-05-08 17:03 UTC, TylerMatteo commented on app/styles/layouts/_l-default.scss
> +      width: 100% !important;
I really would prefer to not add any `!importants`. Future us will thank present us. Are you sure this is necessary? I took it out running your branch locally and things seem to still work.

2024-05-08 19:08 UTC, TylerMatteo approved these changes

2024-05-08 19:39 UTC, merged